In [4]:
import tensorflow as tf
t1 = tf.constant([4.0, 3.0, 2.0])
t2 = tf.constant([3.0, 2.0, 1.0])
dot = tf.tensordot(t1, t2, 1) # 4*3 + 3*2 + 2*1 = 12 + 6 + 2 = 20

with tf.Session() as sess:
    print(sess.run(dot))

20.0


In [6]:
t1 = tf.constant([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
t2 = tf.constant([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]])
mult = tf.matmul(t1, t2)

with tf.Session() as sess:
    print(sess.run(mult))

[[22. 28.]
 [49. 64.]]


In [9]:
m1 = tf.constant([[1, 2], [3, 4]])
m2 = tf.constant([[5, 6], [7, 8]])
e1 = tf.einsum('ij->ji', m1)
e2 = tf.einsum('ij,jk->ik', m1, m2)

with tf.Session() as sess:
    print(sess.run(e1))
    print(sess.run(e2))

[[1 3]
 [2 4]]
[[19 22]
 [43 50]]


In [14]:
# Training to find the minimum of x^2-4x+5
# NOTE: no model formulated. Very simple example, just directly computing a loss.

from __future__ import print_function, division
import os

# Define a trainable variable
x_var = tf.Variable(0., name='x_result')

# Define an untrainable variable to hold the global step
step_var = tf.Variable(0, trainable=False)

# Express loss in terms of the variable
loss = x_var ** 2 - 4.0 * x_var + 5.0

# Find variable value that minimizes loss
learn_rate = 0.1
num_epochs = 40
optimizer = tf.train.GradientDescentOptimizer(learn_rate).minimize(loss, global_step=step_var)

# Initialize variables
init = tf.global_variables_initializer()

# Create the saver
saver = tf.train.Saver()

# Create summary data and FileWriter
summary_op = tf.summary.scalar('x', x_var)
file_writer = tf.summary.FileWriter('log', graph=tf.get_default_graph())

# Launch session
with tf.Session() as sess:
    sess.run(init)
    
    for epoch in range(num_epochs):
        _, step, result, summary = sess.run([optimizer, step_var, x_var, summary_op])
        print('Step {}: Computed result = {}'.format(step, result))
        
        # Print summary data
        file_writer.add_summary(summary, global_step=step)
        file_writer.flush()

    # Store variable data
    saver.save(sess, os.getcwd() + '/output')
    print('Final x_var: {}'.format(sess.run(x_var)))

ValueError: At least two variables have the same name: Variable

In [13]:
# Create session
with tf.Session() as sess:
    # Load stored graph into current graph
    saver = tf.train.import_meta_graph('output.meta')
    
    # Restore variables into graph
    saver.restore(sess, os.getcwd() + '/output')
    
    # Display value of variable
    print('Variable value: ', sess.run('x_result:0'))

Instructions for updating:
Use standard file APIs to check for files with this prefix.
INFO:tensorflow:Restoring parameters from /Users/ksinder/projects/oct-opus/ksinder-playground/output
Variable value:  0.0
